### ISSUE TITLE
User groups

### ISSUE THREAD

**Issue by paavonelimarkka** [N4SJAMK/teamboard-meta#66]
User story: #65 

Draft: ![](https://camo.githubusercontent.com/ff4b848e5629e829a6e11dd0f3731e815dbd2685/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f6a76776571726d74627976746575742f757365725f636f6e74726f6c5f6578616d706c652e706e673f646c3d31)

**Comment by narsuman** [comment]
No groups ...?
